### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by liyuange2007** [emacle/vue-php-admin#1]
您好，非常感谢有这么好的项目。我完全按照您的说明，启动后，就出现了如下提示。研究了好久，也不知道怎么解决。希望能给点意见，谢谢
![image](https://user-images.githubusercontent.com/38851152/192350701-d57fc261-728b-4c30-853a-a135da13dd82.png)

**Comment by emacle** [comment]
https://github.com/emacle/vue-php-admin/blob/master/CodeIgniter-3.1.10/application/config/rest.php#L598
rest.php 文件里配置的,我的配置如下：
```
$config['check_cors'] = true;
$config['allow_any_cors_domain'] = false;
$config['allowed_cors_origins'] = ['http://localhost:9527','http://www.emacle.cf:10000'];
```

**Comment by liyuange2007** [comment]
解决了，感谢
